### ISSUE TITLE
1.0.6 error

### ISSUE THREAD

**Issue by 23doors** [PhantomPhoton/S3-Compatible#26]
Getting error when initiating 1.0.6
2026-04-21 13:10:04.206 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration s3_compatible: cannot import name 'register_feature_id' from 'botocore.useragent' (/usr/local/lib/python3.14/site-packages/botocore/useragent.py)

Using HASS in Docker, latest version

**Comment by freaktechnik** [comment]
And sadly downgrading to 1.0.5 also doesn't work, it's missing some positional session parameter for aiobotocore when loading the config or something (which is presumably a result from the update in 1.0.6).

**Comment by svoop** [comment]
Wow, no matter what device or server, whenever anything builds on to of Boto, it will cause troubles like this issue at some point. :wink: 

Here's the full traceback just in case, on a Home Assistant Yellow:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/s3_compatible/__init__.py", line 8, in <module>
    from aiobotocore.client import AioBaseClient as S3Client
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/client.py", line 16, in <module>
    from botocore.useragent import register_feature_id
ImportError: cannot import name 'register_feature_id' from 'botocore.useragent' (/usr/local/lib/python3.14/site-packages/botocore/useragent.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/s3_compatible/__init__.py", line 8, in <module>
    from aiobotocore.client import AioBaseClient as S3Client
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/client.py", line 16, in <module>
    from botocore.useragent import register_feature_id
ImportError: cannot import name 'register_feature_id' from 'botocore.useragent' (/usr/local/lib/python3.14/site-packages/botocore/useragent.py)
```

**Comment by pierrepinon** [comment]
Hello,

It's a cache issue, I clean `/usr/local/lib/python3.14/site-packages/botocore/__pycache__/useragent.cpython-314.pyc` and restart HA to fix the issue

**Comment by 23doors** [comment]
Good catch! I'm using docker container so only appdata is stored outside of a container. But fixed it by going to where config/custom_components/ are and running:
```
find . -name "__pycache__" -type d -exec rm -rf {} \;
```

and then restarting HA.

Not sure if there is anything that can be fixed by this repo so that these steps are not a must?

**Comment by svoop** [comment]
@pierrepinon Really good catch, thanks a lot! 

On the Yellow, the pychaches are on the OS level which is out of SSH reach by default. However, a **full reboot of the Yellow** rebuilds the caches and thus **fixes the issue**.

**Comment by MyUncleSam** [comment]
> [@pierrepinon](https://github.com/pierrepinon) Really good catch, thanks a lot!
> 
> On the Yellow, the pychaches are on the OS level which is out of SSH reach by default. However, a **full reboot of the Yellow** rebuilds the caches and thus **fixes the issue**.

Most likely the same for HASS OS. I was not able to find the error message but a second reboot fixed it (first reboot for update to 1.0.6 and it was broken, second reboot and it worked again).

**Comment by Bennett-Wendorf** [comment]
I can confirm a reboot of the whole system works for HA OS (at least running in a VM).

**Comment by lennardsc** [comment]
Getting this an Homeassistant Green after restart: Logger: homeassistant.setup
Quelle: setup.py:343
Erstmals aufgetreten: 12:22:19 (1 Vorkommnis)
Zuletzt protokolliert: 12:22:19

Setup failed for custom integration 's3_compatible': Unable to import component: cannot import name 'register_feature_id' from 'botocore.useragent' (/usr/local/lib/python3.14/site-packages/botocore/useragent.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/s3_compatible/__init__.py", line 8, in <module>
    from aiobotocore.client import AioBaseClient as S3Client
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/client.py", line 16, in <module>
    from botocore.useragent import register_feature_id
ImportError: cannot import name 'register_feature_id' from 'botocore.useragent' (/usr/local/lib/python3.14/site-packages/botocore/useragent.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/s3_compatible/__init__.py", line 8, in <module>
    from aiobotocore.client import AioBaseClient as S3Client
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/client.py", line 16, in <module>
    from botocore.useragent import register_feature_id
ImportError: cannot import name 'register_feature_id' from 'botocore.useragent' (/usr/local/lib/python3.14/site-packages/botocore/useragent.py)

**Comment by svoop** [comment]
@lennardsc Have you tried to reboot (not restart) your Green?

**Comment by lennardsc** [comment]
Yes, many times. Same result.

**Comment by PhantomPhoton** [comment]
What version of HomeAssistant (and HomeAssistant OS if applicable) are you running @lennardsc ?

**Comment by ptoump** [comment]
Just a FYI, in HAOS in a VM, it breaks after upgrading the HA core, and gets fixed after a manual reboot.

**Comment by Supertoolz** [comment]
In my HA setup the integration randomly fails and throws the same error message. Disabling and enabling the integration works. However, I fail to see the need for a full restart for one integration to start working again. Even though it might be a cache issue it would be really nice to just restart the S3 entry in the integration or some other way of fixing this instead of relying on a HA restart.

**Comment by svoop** [comment]
@Supertoolz I can confirm this behavior on the Yellow: Every Core update caused this failure after restart and a reboot is necessary to fix it.

**Comment by bugacha** [comment]
Any ideas when is this going to be fixed ? Every Core update causes error until a full shutdown on my side.

**Comment by mailletf** [comment]
I think this PR that was just merged fixes the issue: https://github.com/PhantomPhoton/S3-Compatible/pull/29

**Comment by PhantomPhoton** [comment]
I cut v1.0.7 as a pre-release to test if it fixes it. Feel free to update and report back if it's working for you. HACS -> S3 Compatible -> Three dots in the upper right -> Redownload -> Need a different version -> Release -> v1.0.7

**Comment by pierrepinon** [comment]
I try 1.0.7 and I have already error after HA restart

**Comment by pierrepinon** [comment]
It's not the same error

```python

Enregistreur: homeassistant.config_entries
Source: config_entries.py:787
S'est produit pour la première fois: 08:29:47 (1 occurrence)
Dernier enregistrement: 08:29:47

Error setting up entry homeassistant-pierrepinon for s3_compatible
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 787, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/s3_compatible/__init__.py", line 39, in async_setup_entry
    async with get_session().create_client(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        "s3",
        ^^^^^
    ...<5 lines>...
        verify=data.get(CONF_VERIFY, None) if data.get(CONF_VERIFY, None) != "" else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as client:
    ^
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/session.py", line 35, in __aenter__
    self._client = await self._coro
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/context.py", line 36, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/session.py", line 295, in _create_client
    client = await client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/client.py", line 88, in create_client
    client_args = await self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<12 lines>...
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/client.py", line 301, in _get_client_args
    return await args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<12 lines>...
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/args.py", line 118, in get_client_args
    ruleset_resolver = self._build_endpoint_resolver(
        endpoints_ruleset_data,
    ...<13 lines>...
        auth_scheme_preference,
    )
  File "/usr/local/lib/python3.14/site-packages/aiobotocore/args.py", line 228, in _build_endpoint_resolver
    return AioEndpointRulesetResolver(
        endpoint_ruleset_data=endpoints_ruleset_data,
    ...<7 lines>...
        auth_scheme_preference=auth_scheme_preference,
    )
TypeError: EndpointRulesetResolver.__init__() got an unexpected keyword argument 'auth_scheme_preference'

```

**Comment by pmalek** [comment]
Seeing this in 1.0.7:

```
2026-06-01 22:16:08.470 ERROR (MainThread) [homeassistant] Error doing job: ClientConnectionResetError exception in shielded future (task: None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/aiohttp/_websocket/writer.py", line 240, in _send_compressed_frame_async_locked
    self._write_websocket_frame(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        (
        ^
    ...<8 lines>...
        0x40,
        ^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/aiohttp/_websocket/writer.py", line 151, in _write_websocket_frame
    raise ClientConnectionResetError("Cannot write to closing transport")
aiohttp.client_exceptions.ClientConnectionResetError: Cannot write to closing transport

```

**Comment by PhantomPhoton** [comment]
Alright, so I cut a v2.0.0 pre-release. This removes the boto library entirely and we ship our own minimal S3 client library. This should solve all the startup issues, but may introduce regressions with different servers. Please test and report back if any issues are discovered.

**Comment by b-reich** [comment]
@PhantomPhoton Hetzner S3 still working after upgrading to v2.0.0

**Comment by svoop** [comment]
@PhantomPhoton Dropping Boto is great news, thanks for the effort! I've used all kind of CLI backup solutions over time and Boto was a PITA every time, all the time!

I can confirm v2 to work fine on Hetzner S3 for me as well on a Yellow.

**Comment by pierrepinon** [comment]
@PhantomPhoton Works fine for me too

**Comment by MyUncleSam** [comment]
Mega S4: no outtakes since the 2.0.0 update but I keep an eye on it

**Comment by b-reich** [comment]
Update to 2026.6.2 went fine :)
Thanks!

**Comment by PhantomPhoton** [comment]
I just pushed 2.0.0 as stable, so resolving this, please open a new issue if anything pops up. Thanks everyone for the assistance and patience in getting this sorted out.
